// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __iBATCGH_h__
#define __iBATCGH_h__

#include "iBATCGH_RcppExports.h"

#endif // __iBATCGH_h__
